name: Deploy Lambda and Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2  # Set AWS region
      BUCKET_NAME: main-swanna-bronze  # S3 bucket name
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        mkdir -p package
        pip install -r application/requirements.txt -t package/
        cp application/aapl_ingestion.py package/
        cd package
        zip -r ../lambda_function.zip .
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform -chdir=infrastructure init

    - name: Terraform Validate
      run: terraform -chdir=infrastructure validate

    - name: Terraform Plan
      run: |
        terraform -chdir=infrastructure plan \
          -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        terraform -chdir=infrastructure apply -auto-approve \
          -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Upload Lambda Package to S3
      run: |
        aws s3 cp lambda_function.zip s3://${{ env.BUCKET_NAME }}/lambda_function.zip

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code --function-name AlphaVantageIngestion --s3-bucket ${{ env.BUCKET_NAME }} --s3-key lambda_function.zip --region ${{ env.AWS_REGION }}
