name: Deploy Lambda and Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2  # Update this as needed
      BUCKET_NAME: main-swanna-bronze  # Update with your S3 bucket name

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      working-directory: application
      run: |
        pip install -r requirements.txt -t .
    
    - name: Zip Lambda function
      run: |
        cd application
        zip -r ../lambda_package/lambda_function.zip aapl_ingestion.py *

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform -chdir=infrastructure init

    - name: Terraform Validate
      run: terraform -chdir=infrastructure validate

    - name: Terraform Plan
      run: terraform -chdir=infrastructure plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=infrastructure apply -auto-approve

    - name: Upload Lambda Package to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp lambda_package/lambda_function.zip s3://${{ env.BUCKET_NAME }}/lambda_function.zip

    - name: Deploy Lambda Function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws lambda update-function-code --function-name AlphaVantageIngestion --s3-bucket ${{ env.BUCKET_NAME }} --s3-key lambda_function.zip --region ${{ env.AWS_REGION }}
