name: Print Environment Variables

on:
  workflow_dispatch:

jobs:
  print-env:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Environment Variables
      run: |
        echo "TERRAFORM_STATE_BUCKET=${{ vars.TERRAFORM_STATE_BUCKET }}"
        echo "AWS_REGION=${{ vars.AWS_REGION }}"
        echo "DYNAMODB_TABLE_NAME=${{ vars.DYNAMODB_TABLE_NAME }}"
        echo "BUCKET_NAME=${{ vars.BUCKET_NAME }}"
